## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
from sklearn.model_selection import train_test_split
# 40筆 類別 1 的資料取其中10筆
train_X1, test_X1, train_y1, test_y1 = train_test_split(X[:40,:], y[:40], test_size=10) 
# 160筆 類別 0 的資料取其中10筆
train_X0, test_X0, train_y0, test_y0 = train_test_split(X[40:,:], y[40:], test_size=10)

train_X = np.array( list(train_X1) + list(train_X0) )
test_X = np.array( list(test_X1) + list(test_X0) )
train_y = np.array( list(train_y1) + list(train_y0) )
test_y = np.array( list(test_y1) + list(test_y0) )

print(f'test_X:\n{test_X}')
print(f'test_y:\n{test_y}')

test_X:
[[ 50  51  52  53  54]
 [ 25  26  27  28  29]
 [175 176 177 178 179]
 [ 35  36  37  38  39]
 [ 40  41  42  43  44]
 [ 60  61  62  63  64]
 [170 171 172 173 174]
 [ 55  56  57  58  59]
 [ 30  31  32  33  34]
 [165 166 167 168 169]
 [705 706 707 708 709]
 [465 466 467 468 469]
 [315 316 317 318 319]
 [525 526 527 528 529]
 [390 391 392 393 394]
 [895 896 897 898 899]
 [970 971 972 973 974]
 [905 906 907 908 909]
 [575 576 577 578 579]
 [230 231 232 233 234]]
test_y:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
